# Book settings
# Learn more at https://jupyterbook.org/customize/config.html

title: Few-shot and Zero-shot Learning for Music Information Retrieval
author: Yu Wang, Hugo Flores García, and Jeong Choi
# logo: logo.png # TODO

# Force re-execution of notebooks on each build.
# See https://jupyterbook.org/content/execute.html
execute:
  execute_notebooks: no

# Add a bibtex file so that we can create citations
bibtex_bibfiles:
  - references.bib

# Information about where the book exists on the web
repository:
  url: https://github.com/music-fsl-zsl/tutorial  # Online location of your book
  path_to_book: book  # Optional path to your book, relative to the repository root
  branch: main  # Which branch of the repository should be used when creating links (optional)


# Add GitHub buttons to your book
# See https://jupyterbook.org/customize/config.html#add-a-link-to-your-repository
html:
  use_repository_button: true
  use_issues_button: true
  # google_analytics_id: # TODO

sphinx:
  config:
    html_js_files:
    - https://cdnjs.cloudflare.com/ajax/libs/require.js/2.3.4/require.min.js
